version: 2
project_name: dotfileslinker

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/dotfileslinker
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

# archives configuration with proper format for GoReleaser v2.8.2
archives:
  - id: nix
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
    formats:
      - tar.gz
    ids:
      - dotfileslinker
    allow_different_binary_count: true

  - id: windows
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
    formats:
      - zip
    ids:
      - dotfileslinker
    allow_different_binary_count: true

checksum:
  name_template: "checksums.txt"

# Release configuration
release:
  draft: true # Create release as draft by default
  replace_existing_draft: true
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
