version: 2
project_name: dotfileslinker

before:
  hooks:
    - go mod tidy

builds:
  - id: dotfileslinker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/dotfileslinker
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

# Archives configuration for GoReleaser v2.8.2
archives:
  - id: dotfileslinker
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    ids:
      - dotfileslinker
    allow_different_binary_count: true
    format_overrides:
      - goos: windows
        formats:
          - zip
      - goos: linux
        formats:
          - tar.gz
      - goos: darwin
        formats:
          - tar.gz

checksum:
  name_template: "checksums.txt"

# Release configuration
release:
  draft: true # Create release as draft by default
  replace_existing_draft: true
  prerelease: auto
