version: 2
project_name: dotfileslinker

before:
  hooks:
    - go mod tidy

builds:
  - id: dotfileslinker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/dotfileslinker
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    flags:
      - -trimpath

# Archives configuration for GoReleaser v2.8.2
archives:
  - id: dotfileslinker
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    ids:
      - dotfileslinker
    allow_different_binary_count: true
    format_overrides:
      - goos: windows
        formats:
          - zip
      - goos: linux
        formats:
          - tar.gz
      - goos: darwin
        formats:
          - tar.gz

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# Release configuration
release:
  draft: true
  replace_existing_draft: true
  prerelease: auto
  mode: replace
  header: |
    ## {{ .Tag }} ({{ .Date }})

    このリリースは自動ビルドされています。バイナリの検証には checksums.txt をご利用ください。

    ```
    # Windows
    certutil -hashfile path\to\downloaded\file.zip SHA256

    # macOS/Linux
    shasum -a 256 path/to/downloaded/file.tar.gz
    ```

# Improved reproducibility
gomod:
  proxy: true
  env:
    - GOSUMDB=sum.golang.org
    - GONOSUMDB=github.com/guitarrapc/dotfileslinker-go

# Sign the checksum
signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    artifacts: checksum
    args:
      - "sign-blob"
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
    id: checksum
